export const AUTH_SIGNIN_SUCCEEDED = "AUTH_SIGNIN_SUCCEEDED";
export const AUTH_SET_USER_ID = "AUTH_SET_USER_ID";
export const AUTH_SIGNIN_FAILED = "AUTH_SIGNIN_FAILED";
export const AUTH_SIGNOUT = "AUTH_SIGNOUT";
export const WEATHER_SET_CONFIG = "WEATHER_SET_CONFIG";
export const WEATHER_REMOVE_CONFIG = "WEATHER_REMOVE_CONFIG";
